# 构建docker模版样例
---
# 完整的构建模板标签说明：https://lark.alipay.com/mq4l6o/val2ny/prwhsh
# version表示构建模板.fw.yml的版本，默认值为1.0
version: 1.0
# name表示当前代码仓库的模块名称
name: metrics-server-x86

# variables表示用户自定义的参数，可在构建脚本中引用
# 在触发构建的时候，可通过动态参数覆盖variables中定义的默认值
variables:
  REGISTRY: reg.docker.alibaba-inc.com/cos/metrics-server-amd64
  VERSION: v0.2.1
  ARCH: 'amd64'

privatecloud:
  version: v3

git:
  depth: 1

# machine表示编译机配置，standard表示基于VM编译
machine:
  standard:
    7u2_dockerce_18:
      - default

# scripts中定义构建命令行，通过定义的构建命令行可以构建出artifacts中定义的构建产物
# 在scripts中可直接使用系统环境变量
scripts:
  - sh -x aone_build.sh {{ARCH}} {{REGISTRY}} {{VERSION}}
  - dummy_tgz=dummy-$(date +%s) && touch $dummy_tgz.txt && tar czf $dummy_tgz.tgz $dummy_tgz.txt

# Aone构建目前不支持动态指定镜像版本, 所以artifacts放一个dummy压缩包，确保每次能构建通过
# 真正的镜像产物参考日志输出 {{REGISTRY}}:{动态指定版本}
artifacts:
  packages:
    - dummy-.*.tgz

# notifications定义通知人员列表，目前只支持邮件通知
notifications:
  email:
    - xiaodai.zl@alibaba-inc.com